# Excluded paths
excluded:
  - .build
  - .worktrees
  - build
  - tmp
  - PocketMesh.xcodeproj
  - PocketMesh/Resources/Generated
  - MeshCore/.build
  - MeshCore-references
  - PocketMeshServices/.build
  - fastlane
  - scripts

# Disabled rules
disabled_rules:
  - identifier_name
  - todo
  - nesting
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - non_optional_string_data_conversion
  - optional_data_string_conversion
  - file_length           # Addressed by Workstream C (AppState decomposition)
  - type_body_length      # Addressed by Workstream C (AppState decomposition)
  - type_name             # Catches iOSBLETransport (intentional) and long test names
  - switch_case_alignment  # Triggers on idiomatic single-line switch expressions
  - for_where              # Style preference; where clause can hurt readability

# Thresholds tuned to current codebase. Tighten in future PRs.
line_length:
  warning: 250
  error: 350

function_body_length:
  warning: 200
  error: 500

cyclomatic_complexity:
  warning: 30
  error: 55

function_parameter_count:
  warning: 10
  error: 14

large_tuple:
  warning: 4
  error: 6
