name: PocketMesh
options:
  bundleIdPrefix: com.pocketmesh
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  groupOrdering:
    - order: [App, Views, Services, Models, Protocol, BLE, Persistence, Resources, Tests]

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  PocketMesh:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PocketMesh
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nathanielchung.pocketmesh
        INFOPLIST_FILE: PocketMesh/Info.plist
        DEVELOPMENT_TEAM: L6E4TF9NZ9
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
    dependencies:
      - target: PocketMeshKit
    info:
      path: PocketMesh/Info.plist
      properties:
        CFBundleDisplayName: PocketMesh
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSBluetoothAlwaysUsageDescription: "PocketMesh needs Bluetooth to connect to your MeshCore radio device for off-grid messaging."
        NSBluetoothPeripheralUsageDescription: "PocketMesh uses Bluetooth to communicate with MeshCore mesh network devices."
        NSLocationWhenInUseUsageDescription: "PocketMesh uses your location to share it with contacts in your mesh network."
        UIBackgroundModes:
          - bluetooth-central
        LSRequiresIPhoneOS: true
        UIRequiredDeviceCapabilities:
          - armv7

  PocketMeshKit:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PocketMeshKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pocketmesh.kit
        ENABLE_TESTING_SEARCH_PATHS: YES
        GENERATE_INFOPLIST_FILE: YES

  PocketMeshTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PocketMeshTests
    dependencies:
      - target: PocketMeshKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pocketmesh.tests
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: L6E4TF9NZ9
        CODE_SIGN_STYLE: Automatic

schemes:
  PocketMesh:
    build:
      targets:
        PocketMesh: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: PocketMeshTests
    archive:
      config: Release
